// ============================================================================
// LEDGER SEED — starting examples for the ledger suggester (Ledger Suggest.gs).
// Built from the Rabale Petty Expenses Register (Apr 2025 - Sep 2026): the DESCRIPTION
// part of each narration only (payee names, amounts and dates removed), de-duplicated,
// capped per ledger, and aligned to the rulings in the Ledger Guide (retired ledgers
// mapped to their current home, ambiguous rows dropped). The suggester also learns from
// live approved vouchers, so this file only needs regenerating if the guide's rulings change.
// ============================================================================
var LS_SEED_LEDGERS = ["Birthday Cake & Chocolates", "Conveyance - Others", "Food Exp", "House Keeping Material: Thane & Rabale", "Lodging & Boarding Exp", "Office Expenses", "Packing Material", "Pantry Material", "Parking Charges", "Postage & Courier Charges", "Printing & Stationery", "Repairs & Maintainance-MH03EG0225", "Repairs & Maintenance - MH 04 NB 5087", "Repairs & Maintenance - MH 43 BX 0252", "Repairs & Maintenance - MH04MH4896", "Repairs & Maintenance - MH43 BX 7821", "Repairs & Maintenance - MH43 Bx 7803", "Repairs & Maintenance - Others", "Repairs & Maintenance - Pinning Machine", "Repairs & Maintenance - Shrink Machine", "Repairs & Maintenance - Single Clamp Binding Mach.", "Repairs & Maintenance - Single Clamp Machine ( Bindwell Bluechip)", "Repairs & Maintenance - Single Knife Cutting Mach.", "Repairs & Maintenance - Squaring Machine", "Repairs & Maintenance - Three Knife Cutting Mach.", "Repairs & Maintenance -MH04LQ4014", "Repairs & Maintenance- Cutting Machine", "Repairs & Maintenance- Strapping Machine", "Repairs and Maintenance- Six Clamp Book Binding Mac", "Staff Welfare", "Tea & Coffee", "Transportation Non - GST", "Vehicle Fastag", "Vehicle Operating - Jakat/Toll", "Vehicle Operating - Petrol"];
var LS_SEED = [
[0, "monthly birthday celebration charges paid"],
[0, "birthday cake expenses for the month of june"],
[0, "brithday cake expenses for the month of may"],
[0, "birthday cakes for birthday celebration (monthly"],
[0, "month of mar'26 for employees birthday celebration"],
[0, "purchase cake charges paid for month of feb'26 for celebration employees birthday"],
[0, "brought cakes for employees birthday celebration for the dec month"],
[0, "for birthday celebration in oct 2025 paid"],
[0, "birthday celebration in sep 2025 paid"],
[0, "for brought birthday cake for birthday celebartion of staff (aug month"],
[0, "for brought birthday cake for 03 employees (mar to jul 2025) paid"],
[1, "traveling charges paid for going (bmc school) to take sign and stamp"],
[1, "traveling charges paid for going to maha batco transport by (auto & train"],
[1, "rapido charges paid for kalher to rabale office (warehouse visit"],
[1, "petrol charges paid for going to mulund and vikhroli book delivery ( hand delivery sunil pawar"],
[1, "rapido charges paid for thane office to rabale office (amit sir"],
[1, "traveling charges paid for rabale to ulhasnagar"],
[1, "traveling charges paid for going to mulund book delivery (auto"],
[1, "travelling charges paid for chanakya transport to sanpada to rabale to office (auto-2 person"],
[1, "travelling charges paid for going to sakinaka transport"],
[1, "petrol charges paid for nmmc school stamp & sign receiving (govt tender"],
[1, "traveling charges paid for going to vidya vikas (counter sale"],
[1, "traveling charges paid (meto , train & auto) for 2 persons"],
[1, "traveling charges for going to sakinaka transport by (metro, train & auto) - 2persons"],
[1, "traveling charges paid for going to thane office (auto & train"],
[1, "travelling charges paid for going to mumbra (by auto & train"],
[1, "travelling charges for going to kalyan book delivery to sandeep dheb"],
[1, "travelling charges exps.45/- for going to diva book delivery vidya class to diva stn(auto) paid to ravikiran suryavanshi"],
[1, "traveling charges exps. paid for going to sakinaka transport"],
[1, "travelling charges exps. paid for going to vikas school & ds high school to kisan pandey"],
[1, "travelling charges paid for going to ghatkopar - 2 person ( ghatkopar to rabale by train, rabale to warehouse auto"],
[1, "going to mahila samiti & st. thomas book delivery"],
[1, "travelling charges exps.for going to thane book delivery paid to ravikiran suryavanshi"],
[1, "travelling charges paid for going to charniroad book delivery ( charni road to rabale by train & rabale station to office by auto"],
[1, "travelling charges paid for going to ghatkopar book delivery ( 2 person"],
[1, "travelling charges exps. for going nmmc scholar paid to sandeep dheb"],
[1, "traveling charges for going to mumbra (little orchid) book delivery"],
[1, "travelling charges paid for going for vashi transport ,rabale to rabale office auto"],
[1, "travelling charges paid for going to rk pallavi school (koparkhairane to asangaon train ,vasind to rk pallavi school auto,vasind to vashi train"],
[1, "travelling charges paid for going to tci transport (rabale office to station auto,bhandup to tci auto,tci to bhandup station auto,rabale to office auto- 2 perso"],
[1, "travelling charges paid for going for mankhurd book delivery from mankhurd to rabale train ,rabale to raba;le office auto (2 person"],
[1, "book delivery (trombay to mankhurd (auto),mankhurd to rabale (train),rabale station to office (auto) - 2 person"],
[1, "travelling charges paid for rege tutorial to dombivali station (auto),dombivali station to rabale station (train),rabale station to rabale office (auto) for boo"],
[1, "travelling charges paid for going to byculla bmc press byculla"],
[1, "going to badlapur for delivery (5 persons) panna english school"],
[1, "travelling charges, padgha (pallavi school) ( to"],
[1, "travelling charges paid for pal goilng to vashi transport"],
[1, "travelling charges for going for book delivery"],
[1, "travelling charges paid for goiund to print to print press bycullas press to ptp taxi and other travelling charges"],
[1, "travelling (charges paid for going to vashi transport 2 person"],
[1, "travelling charges paid for kandivali station to thane station, kandivali bbc school to kandivali station"],
[1, "travelling charges for going to thane office (auto"],
[1, "goinf to ghatkopar for book delivery (2 persons"],
[1, "travelling expenses of vikas from sanpada to rabale warehouse"],
[1, "travelling charges paid for balkrishna going to book delivery"],
[1, "petrol charges paid for vishal going to bhiwandi"],
[1, "fot travelling charges paid for going to ulhasnagar book delivery"],
[1, "travelling charges paid for vikas korada for going to dighagaon (transport parcel delivery"],
[1, "travelling charges paid for going to rabale to kalyan for book delievery (excellent classes"],
[1, "travelling charges paid for ashish kesari going to thane office"],
[1, "petrol charges paid for going to sulabh industries"],
[1, "dombivali to vangani & badlapur to ghansoli for book delivery"],
[1, "travelling charges paid for going to book delivery(train return,rabale station kanjurmarg station to class 15 and rabale warehouse"],
[1, "ashish kesari travel for hand delivery"],
[1, "ashish kesari warehouse to rabale statin by auto return & rabale to panvel return for delivery to panvel coaching classes prerna classes"],
[1, "for travelling charges paid for going to alfa tutorial kalyan"],
[1, "travelling charges paid for going to isk godwoon amane (ashish kesari"],
[1, "screening material charges paid & travelling charges paid for thane to rabale (auto"],
[1, "travelling charges paid for navi mumbai order delivery ; (prince das"],
[1, "expenses for going vashi to rabale(train) & rabale station to rabale office(auto"],
[1, "petrol charges paid for going to vashi ; (intra state transportation)(pod machine part"],
[1, "for travelling charegs paid for going to byculla and return"],
[1, "travelling charges paid for going to vashi transport to byculla book delivery"],
[1, "vile parle to rabale (train) rabale station to rabale office (auto)-30 2 person)went for book delivery"],
[1, "travelling charges paid for going to mumbra book parcel (ashish kesari"],
[1, "travelling charges paid for sunil hedge going to mumbra"],
[1, "traveling charges paid for going to majjid (2 person"],
[1, "travelling expnses for tci transport to rabale office (drayas foundation"],
[1, "travelling from vashi for sending cl to pune"],
[1, "travelling different loctions for office work"],
[1, "travelling charges paid for single knife cutting machine part"],
[2, "lunch charges paid for engineers"],
[2, "lunch charges paid for going to neral book delivery"],
[2, "lunch charges paid for going to rk pallavi school & mahila samiti school"],
[2, "lunch charges exps.100/- for pod engineer paid to vikas patil"],
[2, "lunch charges exps. for going to pune (2 persons) paid to shivshankar yadav"],
[2, "lunch charges exps. for going to mahila samiti school and rk pallavi school paid to balkrushna shinde"],
[2, "lunch charges exps. for going to rk pallavi school & south school paid to balkrushna shinde"],
[2, "lunch charges for going to pune delivery"],
[2, "lunch charges paid to labours approved by sandeep sir for late working hours"],
[2, "lunch charges paid approved by sandeep sir -2 person at thane office"],
[2, "lunch charges paid for going to rk pallavi school (padagha) for book delivery"],
[2, "lunch paid for going to rk pallavi school book delivery"],
[2, "breakfast and lunch charges for ratnagiri exhibition"],
[2, "tea charges paid for 3 knife cutting machine mechanic for 2 persons"],
[2, "breakfast & lunch charges paid for going to chiplun (2 person"],
[2, "ordered lunch in pune 2 person"],
[2, "nagpur lunch exp visit for"],
[2, "snacks expenses for bank auditors"],
[2, "breakfast & lunch charges paid for going to baramati (2 days, 4 person"],
[2, "breakfast, lunch, dinner, charges paid for going to jalna book parcel delivery ( to"],
[2, "breakfast, lunch, dinner, charges paid for going to jalna book delivery ( to"],
[2, "lunch charges paid for going to pune book delivery"],
[2, "food exp (2 person) paid for vehicle no.mh04lq4014"],
[2, "tea and snacks for loading & unloading workers"],
[3, "for housekeeping material acid & drain cap"],
[4, "hotel room rent charges paid for going to jalna book parcel delivery ( to ) (hotel almond) gst number not mentioned in invoice"],
[5, "2 locks charges paid"],
[5, "monthly dustbin charges paid for the month of july 2026"],
[5, "12 litre acid charges paid for bathroom cleaning"],
[5, "purchase of 2 incense stick charges"],
[5, "anti slip tape charges"],
[5, "for first aid medical expense i.e. bandage, cipladine cream, dettol & cell"],
[5, "monthly dustbin cleaning charges exps. paid to akash dhawale"],
[5, "medical charges paid for injury to hemant bhoir"],
[5, "nariyal & mala phul exps. for new machine ceremony paid to ravikiran suryavanshi"],
[5, "3nos. disel canels charges paid to ravikiran suryavanshi"],
[5, "medical charges paid for injury to employee (contactor employee) injury to hand during transport unloading"],
[5, "ear plug for machine operators in rabale (10 nos"],
[5, "machine servicing charges paid"],
[5, "monthly dustbin cleaning charges"],
[5, "purchase of flowers,nimbu and coconut for new vehicle ceremony"],
[5, "1/2 kg sweets for new vehicle ceremony"],
[5, "novedat paper stickers and rubber hand gloves"],
[5, "patti,cotton,cipladine cream and bandage charges are paid"],
[5, "stapler pin and stapler machine & auto charges"],
[5, "10 packets of safety pins"],
[5, "morel plastic token coins bought for contract employee identification"],
[5, "morel plastic number token coins purchased for identification of contract employees"],
[5, "bandage charges paid to riya devi"],
[5, "expenses paid for 150 kg heavy duty platform troll charges paid vide bill no: ch1000024786"],
[5, "dustbin cleaning charegs pai d (monthly"],
[5, "acid & medicine charges paid"],
[5, "chair rent charges for pooja (20 chair"],
[5, "pooja material & breakfast charges paid for gudipadava festival"],
[5, "dustbin cleaning charges paid"],
[5, "pooja material charges bandage charges paid"],
[5, "decoration, pooja material & snacks charges paid for mahashivratri festival"],
[5, "rangoli powder charges paid"],
[5, "10 plastic name folders for racking charges paid"],
[5, "8 nos lamine filling book charges paid for keeping art and craft rmc challan copies"],
[5, "decoration material and sweets charges paid for mahashivratri"],
[5, "tea charges paid for dilip sir visit to rabale"],
[5, "bandage charges paid"],
[5, "4 kg sugar 1 ltr pooja oil 1 pack agarbatti for office use"],
[5, "for brought mobile new charger for company"],
[5, "for brought pooja saman incne stick 20 and oil 45"],
[5, "paid garbage monthly charges (nmmc person"],
[5, "for brought pooja material for office"],
[5, "for purchase of colour & rangoli for diwali festival"],
[5, "for purchase of pooja material & travelling charges diwali festival"],
[5, "pooja material,rangoli,small kandil,glass charges paid"],
[5, "for purchase of ganesh murti for vehicle no.mh04mh4896"],
[5, "diwali sweets 2 nariyal diwali festival"],
[5, "diwali kandil charges paid at rabale"],
[5, "pooja material charges paid"],
[5, "medicine charges paid"],
[5, "for labour charges for dustbin cleaning charges paid at rabale"],
[5, "for pooja material charges paid at rabale"],
[5, "medicine charges paid for rabale"],
[5, "purchase mosquito spray charegs paid at rabale"],
[5, "purchase medicine at rabale"],
[5, "purchase medicine & enjectuion charges paid at rabale"],
[5, "chambur cleaning to drainge cleaner tip paid"],
[5, "purchase medicine for warehouse staff at rabale"],
[6, "purchase of 25 kg thread bundle thread charges"],
[6, "8 nos thread bundle charges paid"],
[6, "thread charges and xerox charges paid"],
[6, "screening material charges exp. 1400/- paid to kapil dev"],
[6, "10 kg cotton chindi charges"],
[6, "exps. for thread-8nos. bundel charges paid"],
[6, "purchase of 25 kg thread bundle sutli charges paid"],
[6, "screening charges-notebook- print material paid to kapil dev"],
[6, "5 rolls of kbc suttli"],
[6, "purchase of 25 kgs thread bundle"],
[6, "10kg cotten chindi charges paid"],
[6, "purchase 5 packts for rubber band for brave buddy project"],
[6, "purchase 2 nos rubber band pocket charges paid ; for brave buddy project"],
[6, "packing paper chargespaid for nirmala convert high school (nashik) book packing"],
[6, "screening material charges paid & travelling charges paid for thane to rabale (auto"],
[6, "cotton (5 kg) charges paid"],
[6, "for thread bundle charges paid 07 nos dtl"],
[6, "screening material charges paid & travelling charges paid"],
[6, "fevicol charges paid at rabale for screening book"],
[6, "purchase courier bags fk nsb2 10x13,fk nssb3.5 14x18 vide bill no.2017/2024-25"],
[7, "10 kg sugar charges paid"],
[7, "10 kgs. sugar charges paid"],
[7, "purchased 2 nos scotch bright charges"],
[7, "10 kg sugar charges exps. paid to akash dhawale"],
[7, "10kg sugar charge & 2 vim bar exps. paid to eshwar kalingade"],
[7, "10 kg sugar, 2 aggarbatti & 2 stick colour paper"],
[7, "for 10 kg sugar charges paid to riya devi"],
[7, "purchase of sl spoon se (dmart"],
[7, "kal;ingade for purchase 10kg sugar charges paid 02..04.2026"],
[7, "purchase 10 kg sugar charges paid for rabale"],
[7, "purchase 10kg sugar charges paid"],
[7, "purchase of 5kg sugar charges & sweet charges paid for sankrant celebration paid"],
[7, "brought sugar(5 kg"],
[8, "car parking charges paid for vehicle no.mh04mh4896"],
[9, "courier charges paid for thane office to rabale office( housekeeping material & stationery) to akash dhwale"],
[10, "1 pkt innova sticker for a4 size books charges paid"],
[10, "7 nos box file charges paid"],
[10, "purchase of cello tape (12 pcs"],
[10, "canon 2900 printing teflon change & servicing charges paid"],
[10, "inova stickers (paper stickers 2 nos ) charges paid"],
[10, "285 pcs colour print charges paid"],
[10, "2 pc tape dispenser & 18 pc cello tape charger"],
[10, "2pc tape dispenser & 4pc cello tape paid to akash dhawale"],
[10, "purchase of stationery"],
[10, "stationery exps. charges paid to akash dhawale"],
[10, "fevicol charges require for book pasting"],
[10, "purchase of register for daily basis order entry (1 nos"],
[10, "purchase of register books(qty 15 nos"],
[10, "purchase for spring red charges paid"],
[10, "purchase ball pen charegs paid"],
[10, "purchase of blade, fevikwik, ball pen, stapler and whitner pen stationary charges paid"],
[10, "in and out registration charges paid"],
[10, "brought attandance register"],
[10, "register charges paid(qty 2) in & out"],
[10, "brought orange powder"],
[10, "brought invoice xerox charges"],
[10, "purchase 2 non letter head punching charges paid kalpana ma'am"],
[10, "colour print out for nmmc project (nmmc project"],
[10, "purchase rubber band 2 packet for set machine"],
[10, "zerox charges paid"],
[10, "purchase 10 nos box file (purchase for project) ; (68*10=680) qty;10"],
[10, "purchase of a4 size register for daily trip charges"],
[10, "small staplar pin charges paid"],
[10, "purchase marker pen & cutter charges paid"],
[10, "bought a4 size paper"],
[11, "vehicle servicing charges paid for vehicle no: mh03eg0225"],
[11, "2 tyres and tubless valve charges paid to poooja tyres"],
[11, "tyre puncture repair charges paid to anish kumar"],
[11, "breake pad & labour charges paid for vehicle no.mh03eg0225"],
[11, "puc charges paid for vehicle no: mh03eg0225"],
[11, "& brake service chargs paid for vehicle no.mh03eg0225"],
[11, "tyre puncture fitting charges paid for vehicle no.mh03eg0225"],
[11, "rto passing & fitness certificate charges paid for vehicle no.mh03eg0225"],
[11, "for tyre puncture charges paid for vehicle no.mh03eg0225"],
[11, "purchase 155r13 mrf tyre smr m 154 tube less qty:2 pcs @rate 3800 (incl of tax) vide bill no.48923"],
[11, "new battery charges paid for vehicle no.mh03eg0225"],
[11, "battery charging charges paid for vehicle no.mh03eg0225"],
[11, "wheel alignment charges paid for vehicle no.mh03eg0225"],
[11, "tyre puncture and fittings charges paid for vehicle no.mh03eg0225"],
[11, "new brake pad & waiper charges paid for vehicle no.mh03eg0225"],
[11, "cluth plate change & labour charges paid for vehicle no.mh03eg0225"],
[12, "purchase of cable for charging point of new vehicles (mh04 nb 5087 & mh04 nb 5088"],
[12, "painting charges vehicle number plates,stop,goods carrier and companies name both side and 3 logos printing both side both vehicle no. mh 04 nb 5087 & mh 04 nb "],
[13, "spin & wiser charge paid for leaf spring for veh.no: mh 43 bx 0252"],
[13, "radiator fiting charger , oil change , oil fitter & sprint charges paid for vehicle no: mh 43 bx 0252"],
[13, "10 ltr def oil charges paid for vehicle no: mh43bx0252"],
[13, "radiator cup charges paid for veh.no : mh43bx0252"],
[13, "radiator servicing charges for vehicle no: mh43bx0252"],
[13, "3 nos. nut bolts , 6nos spray washer , 1 ltr engine oil charge paid for vehicle no: mh 43 bx 0252"],
[13, "for def charges paid for vehicle no.mh 43 bx 0252"],
[13, "new aamron battery for vehicle no.: mh43bx0252"],
[13, "repaire mirror charges paid for vehicle no.mh43bx0252"],
[13, "shutter repairs charges paid for vehicle no.mh43bx0252"],
[13, "pana charges paid for vehicle no: mh43bx0252"],
[13, "puncture fitting charegs paid for vehicle no.mh43bx0252"],
[13, "tyre fitting charges paid for vehicle no.mh43bx0252"],
[13, "rto passing & fitness certificate charges paid for vehicle no.mh43bx0252"],
[13, "for 10ltr def tata charges for vehicle no.mh43bx0252"],
[13, "cluth set, cluth oil set, buster, cluth pipe & pad, nutbolt & labour charges paid for vehicle no.mh43bx0252"],
[13, "cluth bustur lower, cluth pipe, oil ringset, bering oil fitter & labour charges paid for vehicle no.mh43bx0252"],
[14, "condenser pipe fitting charges for vehicle number .mh 04 mh 4896"],
[14, "purchase of condensor pipe 1 nos & 1 ltr coolant charges paid for vehicle number mh 04 mh 4896"],
[14, "light wiring & one rely change charges paid"],
[14, "purchase of plastic transparent and black sheet & ropes charges for vehicle no. mh 04 mh 4896"],
[14, "puncture charges paid for vehicle no. mh04 mh 4896"],
[14, "vehicle servicing charges mh 04mh 4896"],
[14, "vehicle puc charges paid for vehicle no: mh04mh4896"],
[14, "repaire vehicle no.mh04mh7896 engine oil, oil filter, brake pads front, air filter, & labour charges"],
[14, "for tyre puncture fitting and patch charges paid for vehicle no.mh04mh4896"],
[14, "cluth plate, ribit, preshor plate cutt, privil bush, stering kit, brering set, & labour charges paid for vehicle no.mh04mh4896"],
[15, "for reflector charges paid for vehicle number mh 43 bx 7821"],
[15, "stem value charges (punture) paid for vehicle no: mh43bx7821"],
[15, "vehicle scaning charges paid for vehicle no.mh43bx7821"],
[15, "purchase vehicle part & repairs charges for vehicle no.mh43bx7821"],
[15, "repairs type puncher charges paid for vehicle no.mh43bx7821"],
[15, "vehicle scanning, line checking and wd40 charges paid for vehicle no. mh43bx7821"],
[15, "purchase mrf tyre for vehicle no.mh43bx7821 vide bill no.50918"],
[15, "purchase tyres for vehicle no.mh43bx7821 ; (215/75r15 apollo end.lt tl) qty:11 @rate 5762.71(exc.gst"],
[15, "for break pad change of vehicle charges paid for vehicle no.mh43bx7821"],
[15, "puc charges vehicle no.mh43bx7821 (puc from to"],
[15, "purchase 215/75r15 jk steelking lt tyre, 215/75r15 jk tube qty:2 @rate 6700, 300 (incl of tax) vide bill no.48924 (vehicle charges paid for vehicle no.mh43bx782"],
[15, "cluth plate set,cluth berings grees, nut bolt, all filter check, repaire service kit & labour charges paid for vehicle no.mh43bx7821"],
[16, "vehicle servicing & labour charges paid for vehicle no: mh43bx7803"],
[16, "e- starter exchange & labour charges paid vehicle no: mh43bx7803"],
[16, "vehicle service charges vehicle no: mh43bx7803"],
[16, "vehicle servicing charges exps. for vehicle no: mh43bx7803"],
[16, "vehicle servicing charges like clutch setting ,brake setting and air tyre for vehicle no. mh 43 bx 7803"],
[16, "vehicles repairing charges paid for vehicle no.:mh43bx7803"],
[16, "puc charges for vehicle no.: mh43bx7803 to shrikant das"],
[16, "scanning charges paid for vehicle no.:mh43bx7803"],
[16, "engine oil, oil filter, air filter diesel filter charegs & labour charges for vehicle no.mh43bx7803"],
[16, "new starting rod & horn work & labour charges paid for vehicle no.mh43bx7803"],
[16, "starter repaire charges paid for vehicle no.mh43bx7803"],
[16, "tyre puncher & fitting charges paid"],
[16, "clutch plate repairs charges (vehicle no.mh43bk7803"],
[16, "puchase jk tyres & jk tubes for vehicle no.mh43bx7803 (qty.2pcs) vide bill no; 49429"],
[16, "expenses engeen oil, oil filter, break pad dram, oil filter ring, ribit disk cutting & labour charges paid for vehicle no.mh43bx7803"],
[16, "2 nos breake disks, all brake pad change & labour charges paid for vehicle no.mh43bx7803"],
[16, "purchase of 215/75r15 apollo end lt tyre (qty 01 pcs)* 5312.50 rate"],
[16, "puncture fitting charges paid for vehicle no.mh43bx7803"],
[16, "puc charges vehicle no.mh 43bx 7803(puc period from to"],
[17, "6 pc ln key nuts & 2pc tapper pin charger paid for cutting mach"],
[17, "no & emergency switch charges paid for lift"],
[17, "water purifier servicing charges paid"],
[17, "shead rent & maintenance charges paid (6 month"],
[17, "charges paid for mseb new transformer ( transformer breakdown"],
[17, "1 pc lock & 2 register attendence paid"],
[17, "bathroom pump charges paid"],
[17, "material charges paid for lift and up5 invertor paid to kapil dev"],
[17, "drainage cleaning charges ( chember cleaning -2"],
[17, "3 kg cement purchase for draining chembers repairing charges paid"],
[17, "exps. for 3 pin plug charges paid to eshwar kalingade"],
[17, "10 kg cotton chindi for cleaning machinery exps. paid to kapil dev"],
[17, "diesel charges exps. for (pod) machine cleaning paid to deepak sane"],
[17, "repair and servicing charges paid for goods lift"],
[17, "purchase of 10w led bulb charges (1 nos"],
[17, "10 kg cotton bought for machine cleaning"],
[17, "hp laserjet 1020 printer service charges paid"],
[17, "ap3 grease and lift services and greasing charges"],
[17, "sealing fan material charges"],
[17, "repairing charges paid for water purifier filter"],
[17, "5 nos. capacitor charges for fan"],
[17, "servicing charges paid for hp 1020 printer machine to akash dhawale"],
[17, "expenses 4nos. skp bearings for all machines and handgloves for workers paid"],
[17, "10 ltr oil gaire oil charges paid"],
[17, "bering, bolt & teaping charges paid for binding machine"],
[17, "purchase ponds powder & chindi for all machine charges paid"],
[17, "2 box panna for all machine charges"],
[17, "tyre puncher servicing charges paid for vehicle no: mh03eg0225"],
[17, "10kg cotton chindi for cleaning all machines"],
[17, "key holder metal box charges paid"],
[17, "hp 1020 printer service charges paid"],
[17, "pucrhase cotton chindi"],
[17, "note book preasure machine gear patti change & service charges (squaring machine full servicing & patti change"],
[17, "for printer repaire bcb and online deparment"],
[17, "for brought pinning wire (qty 50) ln key expenses paid"],
[17, "h.t greece & shf greece for all machine"],
[17, "mahcine repairs preasure machine squarity machine unit change"],
[17, "for purchase lock for bathroom paid"],
[17, "for expenses for screw charges paid for binding machine"],
[17, "rack system sampleling charges paid"],
[17, "pu pipe & joint material charges paid for compreser machine"],
[17, "for expenses for srit pin charges paid for binding machine"],
[17, "2 nos ponds powder charges paid for cutting machine"],
[17, "for cutter patti brazing charges paid for"],
[17, "for hydrailic oli charges paid for all machine (inv no.1"],
[17, "grees charges paid for all machine"],
[17, "for replacement of wire rope & lift servicing charges paid(noble engineering works"],
[17, "for creasing machine repaire charges"],
[17, "new pc connection & fan repaire charges paid"],
[17, "printer repair charges (hp laserjet 1005 teflon & pressure roller change, canon lbp 2900 teplon change qty:2 @rate 1200, 750/"],
[17, "power staring oil charges paid for all vehicle"],
[17, "drainage cleaning charges paid"],
[17, "purchase 3 nos ponds powder charges paid"],
[17, "celing fan rewanding and fititing charges"],
[17, "knife sharpening charges & travelling charges"],
[17, "electricion charges paid for pollar cutting machine motor fitting & electric problem ckecking"],
[17, "water brush,patti,acide chaerges paid"],
[17, "tester charges paid at rabale"],
[17, "ponds powder & cotton chindi charges paid at rabale"],
[17, "brought nylone rope for all vehicle"],
[17, "electricion charges paid for new miter change r-707"],
[17, "brought 25 mtr wire,nut bolt & wire tep charges and electrician charges paid"],
[17, "for candle change of water filter and servicing charges done by ds enterprises"],
[17, "hp leaserjet 04 printer repaire & service charges paid at rabale"],
[17, "carbon charges paid for cutting machine"],
[17, "purchase of polish paper charges paid"],
[17, "paper dust bag charges paid"],
[17, "10 bundle strinling wire charges & travelling charges paid"],
[17, "wd 40 charges for all machine"],
[17, "brought ponds powder for cutting machine charges paid"],
[18, "pinning wire charges paid to kisan pandey"],
[18, "pinning wire charegs paid for pinning machine & travelling charges paid"],
[18, "10 nos pinning wire for pinning machine, 4 nos carbon for single knife cutting machine, al key bolt for 3 knife cutting machine"],
[18, "24 no. wire pinning machine, /off switch for single knife cutting machine, dazzit spary & heater tap for shrink machine,travelling charges"],
[18, "repairs pining machine service charges & part wire charges paid"],
[19, "motor binding , bearing change for automatic shrink machine and new tubelight and connection wire charges paid"],
[19, "3 rolls heater patti and vid 40 & ok5 2601 spray charges paid for shrink machine"],
[19, "wd40 spray and heating tape charges paid for shrink machine"],
[19, "sealing tape charges paid for shrink machine"],
[19, "shrink machine service charges (filament socket, corner block, filament wire, teflon tape, & service charges"],
[19, "shrink machine material (teflon tape, mould sprey"],
[19, "for auto l ruler conter charegs and fitting charges paid for shrink machine"],
[19, "for old shrink machine servicing charges paid"],
[19, "brought 55 bolt 1pic for shrink machine"],
[19, "conveyer belt charges paid for new shrink machine (conveyer belt 2100x300x1.5mm"],
[19, "bearing & nut bolt shrink machine charges paid"],
[19, "2.5 a smps charges for shrink machine electric part & labour charges"],
[19, "convyer belt charges for shrink machine & labour charges paid"],
[20, "repair charges of single clamp binding machine"],
[20, "single clamp machine repair charges paid"],
[20, "8 nos bolt chargespaid for single clamp binding machine"],
[20, "single clamp binding machine material & side glue service charges paid"],
[20, "1 hp moter rewinding charges paid for single clamp binding machine (irfan electric) qty:01"],
[20, "electricion charges paid for single clamp binding machine"],
[21, "repair charges of single clamp binding machine (new ) bindwell bluechip & ceiling fan purchased and ceiling fan retaled expenses done"],
[22, "delta plus switch charger for cutting machine single knief & labour charges exps. paid to kapil dev"],
[22, "hydroli daab chain services for syfa cutting machine (single knife) and labour charges included"],
[22, "winding, motor fitting & bearing skf weighht soldering for single clamp machine charges paid"],
[22, "pump fitting, new belt change, hydrolic oil filter charges paid for syfa cutting machine (single knife) and labour charges included"],
[22, "glass fuse for single knife cutting machine"],
[22, "gearbox open and oil seal fitting charges paid for 1 knief cutting machine"],
[22, "machine table lavel machanic charges paid for single knife cutting machine"],
[22, "for lock charges,belt charges paid for single knife cutting machine"],
[22, "electrician charges paid for single knife cutting machine"],
[22, "coil winding charges & labour charges paid for single knife cutting machine (36 inch"],
[22, "oil seal changes machine charges paid"],
[22, "2 pic domenult charges paid"],
[23, "servicing charges paid for squaring 2pcs of hydraulic edge square machine"],
[24, "bearing charges paid for 3 -knief cutting machine"],
[24, "machine part brazing charger paid for three knief cutting machine"],
[24, "oil leaked servicing charges exps for old cutting 3 knief machine paid to kapil dev"],
[24, "ponds powder for 3 knief cutting machine"],
[24, "ceiling fan winding for 3 knief cutting machine and 3 knief electric panel problem , 708 light problem & pod/ac - light problem"],
[24, "expenses for three kinife cutting machine -oil set fitting & labour charges paid to kapil dev"],
[24, "hydrolic clamp book problem and book service ,hydrolic pipe and firal fitting new copper,hydroli oil set new fitting and labour charges for 3 knief old cutting "],
[24, "nylon tube (2 nos) and brass ferrule charges (12 nos) paid for old 3 knief cutting machine"],
[24, "replacement of new timmer ,main motor belt problem setting and labour charges paid for 3 knief cutting machine"],
[24, "service charges for three knife cutting machine due to electric problem"],
[24, "ferul 6 mm and nylone pipe charges paid for three knife cutting machine"],
[24, "m/c up and down problem, calmp coid replacement and new spring set charges and labour charges for three knife cutting machine"],
[24, "pump services, pump new oil and labour charges for three knife cutting machine"],
[24, "tapping bush charges paid for 3 knife cutting machine"],
[24, "3 pcs flat belt charges paid for 3 knife cutting machine"],
[24, "purchase screen material charges paid & thane to rabale direct charges paid"],
[24, "hydrolic oil pump nylon ceil repair charges paid for 3 knief cutting machine and labour charges"],
[24, "kisan pandey for pinning machine 10 nos nilon patti for single knife cutting & 2 nos kilon putting for 3 knife cutting machine (travelling charges"],
[24, "labour charges paid for 3 knife cutting machine hydrolic pipe fitting"],
[24, "2 nos hydyrolic pipe and nose clip for 3 knife cutting machine"],
[24, "14 nos paper and 3 nos taplon tap charges paid for 3 knief cutting machine"],
[24, "electric pannel repairs and charges paid for 3 knief cutting machine"],
[24, "electricion charges paid for three knife cutting machine & squaring machine (switch problem checking"],
[24, "ln key nut charges paid for 3 knife cutting macine"],
[24, "for 2 pair connetor charges for 3 knife cutting machine"],
[24, "for brought nut bolt screw,l n key nut & l n key charges for 3 knife cutting machine"],
[24, "transformers winding and repairing charges paid (for three knife machine"],
[24, "for ms plate for 3 knife cutting machine"],
[24, "for electrician charges for 3 knife cutting machine(electric problem chcking"],
[24, "ratifir charge paid for three knife cutting and petrol charges"],
[24, "24 pc 14x 4 patti for 3 knife cutting, 4 pc mis wire for pinning machine, 2 pc copper carbon for single knife cutting machine & travelling expenses paid"],
[24, "repairs done for 3 knife cutting machine"],
[24, "screw charges paid for cutting machine"],
[24, "painting brush, m seal, aratitle & scrue charge paid for three knife cutting"],
[24, "for l n key nut charges for 3 knife cutting machine"],
[24, "12 pic sirclip & scale charges paid for 3 knife cutting machine"],
[24, "hydrolic pipe and ferul nut charges paid for 3 knife cutting machine"],
[24, "electrician charges paid for 3 knife cutting machine"],
[24, "hyadrolic adatoper and pipe charges paid for 3 knife cutting machine (old"],
[25, "tubles puncture charges paid for vehicle no. mh 04 lq 4014"],
[25, "tube puncture charges paid"],
[25, "headlight bulb and fiting labour charges paid for vehicle no: mh 04 lq 4014"],
[25, "new tyre for vehicle number mh04lq4014 charges"],
[25, "vehicle puncture and patch charges paid"],
[25, "new tyre charges paid for vehicle no. mh 04 lq 4014"],
[25, "vehicle side mirror charges for vehicle no.: mh04lq4014"],
[25, "vehicle repairing charges for vehicle no.: mh04lq4014"],
[25, "purchase of tg 550 12 voct vehicle battery charges paid for vehicle no.:mh04lq4041"],
[25, "purchase mrf tyre for vehicle no.mh04lq4014 vide bill no.50919"],
[25, "purchase mrf tyre for vehicle no.mh04lq4014"],
[25, "rto consultant charges & reflecting tape confomirs to cmvr charges paid for vehicle no.mh04lw4014 (certificate of fitness transport vehicle charges certificate "],
[25, "tyre puncture & patch vehicle no.mh04lq4014"],
[25, "for engine oil,filter break pad and disk air fiter patta allservice charges paid for vehicle no.mh04lq4014"],
[25, "for punchture fitting charges paid for vehicle no.mh04lq4014"],
[25, "for air checking charges paid for vehicle no.mh04lq4014"],
[25, "steering material & repaire charges paid for vehicle no.mh04lq4014 (labour charges"],
[25, "cluth plate, ribit, preshor plate cutt, privil bush, stering kit, brering set, & labour charges paid for vehicle no.mh04lq4014"],
[25, "side glass left side for vehicle no.mh04lq4014 (m.k. motors"],
[25, "new clutch pleit,brake pads tvs,clutch bush, brake oil for vehicle no.mh04lq4014"],
[26, "2 pc ponds for cutting machine & 10 kg cotton chindi for mach. cleaning"],
[26, "knief carbon holder servicing & labour charges paid for spy cutting machine"],
[26, "hydrolic block kit replacement & 2 nos. spring charges for spy cutting machine eps. paid to kapil dev"],
[26, "a-68 belt and xo, blade charges paid for cutting machine"],
[26, "gear box oil change replace oil & cluth bush charges paid for seypa cutting machine"],
[27, "1. nos kevis belt , 1 nos m28 belt & strap guide ( machine part) & maintenance charges paid for strapping machine"],
[27, "strapping machine servicing charges exps. paid to kapil dev"],
[27, "strapping machine repair charges paid to kapil dev"],
[27, "repair charges of strapping machine charges"],
[27, "repairing charges of strapping machine"],
[27, "straping machine repaire charges paid"],
[28, "purchase of 24 pcs of six clamp bearing for bindwell binding machine"],
[28, "six clamp machine"],
[28, "5 nos nuts (screw) and 1 nos battery charges paid for 6 clamp binding machine"],
[28, "m-seal charges paid for 6 clamp binding machine"],
[28, "for gress machine,skf gress 1 kg,copper legs 12pc charges for six clamp binding machine"],
[28, "for grub screw for six clamp binding machine a & b"],
[28, "key screw charges paid for 6 clamp binding machine"],
[28, "gum roll & electric panel material charges paid for six clamp binding machine"],
[28, "for tee allen key charges paid for 6 clamp binding machine"],
[29, "10 jar watter bottle charges paid"],
[29, "10.nos. drinking water jar charges exps. paid to akash dhawale"],
[29, "10 nos. water jar charges exps. paid to akash dhawale"],
[29, "sweets charges for new machine ceremony paid to akash dhawale"],
[29, "fun friday charges at rabale"],
[29, "10 ltr water jar"],
[29, "new vehicle consercation cermony"],
[29, "drinking water jar charges"],
[29, "drinking water jar purchase charges paid to akash dhawale"],
[29, "water jar chargees"],
[29, "charges paid for gift hamper for fun friday celebrations paid to akash dhawale"],
[29, "purchase water bottle charges paid (1 packet; 48 bottels"],
[29, "purchase kitkat chocolates & gift charges paid for womens day celebration"],
[29, "tea charges paid for pod machine engineer"],
[29, "2 water bottle charges paid for amit sir"],
[29, "water bottle and tea charges paid for bindwell executive"],
[29, "5 nos 20 lit drinking water jar charges paid"],
[29, "for brought water cane bottles for office(qty 6*50 rs"],
[29, "dustbin cleaning worker"],
[29, "for pooja material for dassara festival and travelling charges"],
[29, "for dance choregrpher fee charges paid (flawless dance & fitness studio-sector 16,ghansoli navi mumbai 400701)(song 2*4500"],
[29, "10 nos drinking water 20 ltr jar charges paid"],
[29, "tea charges paid for creasing machine machanic"],
[29, "tea charges paid for sandeep sir hr"],
[29, "tea, breakfast, sweets & cake charges paid for sukhdev sir sendoff (rabale to thane shift) function"],
[29, "tea charges paid for banker visit in rabale"],
[29, "7 nos drinking water 20 ltr jar charges paid (qty:07 rate@50 per"],
[29, "tea charges paid for sandeep sir hr & sagar sir (admin"],
[29, "water charges paid for rabale"],
[29, "purchase of polish paper & ponds powder charges paid"],
[29, "ordered 10 nos drinking water 20ltr jar charges paid"],
[29, "purchase pof gas mask set (piece2) for pod department at rabale (inv no. gj2250625885-2425,gj2250625885-2425"],
[30, "tea charges paid for visitors (3 nos"],
[30, "tea charges paid for pod engineers"],
[30, "tea charges for tushar sir"],
[30, "tea expenses for bipin bhai tushar sir sandeep"],
[30, "tea expenses for bank auditors (4 person"],
[30, "for tea expenses for axis bank employees and 2 ranks vendor"],
[30, "tea expenses for barcode vendor"],
[30, "tea for racking vendor, bipin bhai+2"],
[30, "tea charges paid for packing vendor"],
[30, "tea charges paid for konica and ruching vendor"],
[30, "for tea charges paid for sagar sir"],
[30, "for tea charges paid for binding machine engineer"],
[30, "for tea charges for sandeep sir hr and pod engineer"],
[30, "tea charges paid for cutting machine engineer"],
[30, "tea charges paid for cutting machine mechanic"],
[30, "for tea charges paid for binding machine machanice"],
[30, "tea charges paid for cutting machine machanice"],
[30, "tea charges paid for guest visit in rabale"],
[30, "tea charges paid for dilip sir"],
[30, "tea charges paid for cutting machine machanic"],
[30, "tea charges paid for internet cable charges worker"],
[30, "tea charges paid for new product training"],
[30, "for tea charges paid for mechanic"],
[30, "for tea charges paid for software vendor"],
[30, "for tea charges paid for rack system vendor"],
[30, "for tea charges paid for lift repaire mechanice"],
[30, "tea charges paid for mayur lilakar sir (new product training"],
[30, "tea charges paid for machine machanic (pod"],
[30, "tea charges paid for machanic"],
[30, "tea charges paid for cutting machine machnices"],
[30, "tea charges paid for binding gum excutive visit"],
[30, "tea charges paid for machnices"],
[30, "tea charges paid for sandeep sir hr"],
[30, "tea charges paid for mahatab madam \""],
[30, "tea charges paid at rabale"],
[30, "tea chaerges for machenic"],
[30, "tea charges for machine machanic"],
[30, "tea charges for sandeep sir hr machine machanic"],
[30, "tea charges paid for tushar sir & sandeep sir hr"],
[30, "tea charges paid for sagar sir admin"],
[30, "tea charges paid for machanic & sandeer hr"],
[30, "tea charges paid for electrician"],
[30, "tea charges paid for machnic"],
[30, "tea charges paid for electricion"],
[30, "tea charges paid"],
[30, "tea charges paid for fuji engineer"],
[30, "tea charges paid for chair repair mechanic"],
[30, "tea charges paid for (tech bond gum vendor executive"],
[30, "ordered tea charges paid for machanic"],
[30, "sunday working tea exp for dilip sir and support staff"],
[30, "ordered tea charges paid for tushar sir & thane office staff"],
[31, "hamali charges for veh.no: mh04lq4014"],
[31, "porter charges paid for going to sakinaka transport & sheetal transport"],
[31, "porter charges paid for taloja to rabale office. (bmc kiting box delivery"],
[31, "porter charges paid for rabale to ambernath book delivery"],
[31, "porter charges paid for the period of to ( thane office book delivery,vashi transport book delivery, dattadeep classes nerul book delivery,pioneer book delivery"],
[31, "porter charges paid for rabale to vikhroli ( dr babasaheb vidhyalaya"],
[31, "porter charges paid for rabale to thane book delivery"],
[31, "porter charges paid for rabale to rishabh bhagnari home book delivery"],
[31, "porter charges paid for rabale to santacruze book delivery"],
[31, "transportation charges paid for going to rabale to grant road book delivery to deepak sane"],
[31, "porter charges exps. for ghansoli to sion east book delivery paid to ravikiran suryavanshi"],
[31, "going pawane to rabale office for book delivery"],
[31, "porter charges paid for rabale to amboli book delivery"],
[31, "porter charges paid for going to rabale to thane"],
[31, "porter charges paid for rabale to borivali west book delivery"],
[31, "porter charges paid for going to grant road book delivery"],
[31, "porter charges paid for rabale to vile parle (aaichi shala"],
[31, "porter charges exps.for ghansoli to rabale -(chalkboard slate delivery) paid to manoj pasi"],
[31, "rabale to vashi transport"],
[31, "porter charges paid for karnavat classes to rabale to ravikiran suryavashi"],
[31, "porter charges exps. for pawane to rabale paid to rupesh bhoravkar"],
[31, "porter charges exps. for rabale to rabale transport paid to sandeep dheb"],
[31, "porter charges paid for rabale to vashi transport to ravikiran suryavanshi"],
[31, "late night loading charges paid to ravi suryavanshi"],
[31, "porter charges rabale to andheri book delivery (jk shah"],
[31, "porter charges paid for going for rabale to vombivali book delivery"],
[31, "porter charges paid for going for book delivery from rable to mumbra book delivery"],
[31, "porter charges paid for rabale to airoli (avalon leraning solution"],
[31, "porter charges paid for byculla bmc press to mahape (narrali gaon"],
[31, "dapode to rabale office book delivery"],
[31, "porter charges for rabale to borivali book delivery (mel training"],
[31, "porter charges paid for bhiwandi to rabale (navjeevan books - rajesh sir"],
[31, "porter charges paid for rabale office to tci transport rabale for book delivery"],
[31, "portere charges paid to sandeep dheb rabale to vashi transport"],
[31, "rabale office to thane office"],
[31, "woodsnipe delivery"],
[31, "bandra (purshotam"],
[31, "extra hamali charges paid for lr no.: 1022046, 743294, 1005011 vehicle no.: mh43bx0252"],
[31, "transportation return parcel charegs paid for vehicle no.mh43bx0252 (intra state transportation"],
[31, "porter charges paid for rabale to borivali (our lady of vallinkani school) & hamali charges paid"],
[31, "porter charges paid for rabale to ulwe & hamali charges paid"],
[31, "forklift supplied charges paid"],
[31, "transportation return parcel charges paid for vehicle no.mh43bx0252 & wating charges"],
[31, "porter charges paid for going to masjid transport"],
[31, "transportation hamali charges paid for vehicle no. mh03eg0225"],
[31, "auto rent fo goregaon to rabale book delivery (yellow drawing book"],
[31, "porter charges for going to rabale to thane to book delievery (pioneer book store"],
[31, "porter charges paid for thane to rabale jupni delievery"],
[31, "porter charges paid for rabale to shraddha chasses vikhroli book delievery"],
[31, "ghansoli to rabale (masala board- art & craft-bmc) (tender"],
[31, "for auto charges paid for woodsnipe book delivery"],
[31, "porter charges paid for new student agency book"],
[31, "for transportation parcel hamali charges paid for vehicle no.mh04mh4896 (intra state transportation"],
[31, "for porter charges paid for rabale to vashi transport delivery"],
[31, "for loading and unloading charges (750*4 person"],
[31, "intra state transaction"],
[31, "loading & unloading charges paid for vehicle no.mh43bx0252"],
[31, "porter charges paid for rabale to fatak transport vashi & hamali charges paid"],
[31, "tosandeep dheb for porter charges paid for rabale to prabhat transport"],
[31, "porter charges paid for vidya vikas school vikhroli to rabale"],
[31, "porter charges paid for rabale to sakshar academy vile parle"],
[31, "porter charges paid for rabale to thane office book parcel delivery"],
[31, "porter charges paid for rabale to vidyarthi sales agencies girgoan book delivery"],
[31, "porter charges paid for rabale to vikas roadline and hamali charges"],
[31, "porter charges paid for rabale to vikroli & travelling charges paid (vikas korada"],
[31, "paper bundle loading charges for vehicle no.mh04lq4014"],
[31, "loading and unloading charges for dkt school alibaug book delivery(2 person"],
[31, "porter charges paid for rabale to kalwa & mumbra for book delivery"],
[31, "porter charges paid for rabale to andheri for book delivery & travelling charges paid for andheri to rabale"],
[31, "labour for loading & unloading for govt. project(hired from outside for delivery"],
[32, "fastag charges paid for vehicle no: mh 04 mh 4896"],
[32, "fastag charges paid for vehicle no: mh04mh4896 paid to sandeep dheb"],
[32, "fastag recharge expense for vehicle no. mh 03 eg 0225"],
[32, "fastag charges exps. paid to sandeep dheb"],
[32, "fastag charges (padga) for vehicle no.: mh04 mh 44896"],
[32, "fast tag charges (mh 43 bx 7803"],
[32, "for fasttag recharge charges paid for vehicle no. mh03eg0225"],
[32, "airoli monthly toll charges paid for vehicle no.mh43bx7803"],
[32, "fasttag recharges charges paid for vehicle no.mh03eg0225"],
[32, "fastag recharges for vehicle no.mh04lq4014"],
[33, "airoli toll charges paid for veh.no: mh43bx7821"],
[33, "airoli toll charges paid for vehicle no: mh04mh4896"],
[33, "lbs toll charges paid for vehicle no: mh04lq4014"],
[33, "airoli toll charges paid for vehicle number mh 04 mh 4896"],
[33, "dahisar toll charges paid for vehicle no.mh 04 lq 4014"],
[33, "vashi & airoli toll charges paid for vehicle no: mh 43 bx 7821"],
[33, "airoli & dahisar toll charges paid for vehicle no: mh43bx7821"],
[33, "mbt road toll charges paid for vehicle no: mh04lq4014"],
[33, "dahisar & airoli toll charges paid for vehicle number mh 43 bx 7821"],
[33, "dahisar & toll charges paid for vehicle number mh 43 bx 7821"],
[33, "airoli toll charges paid"],
[33, "dahisar toll charges paid for mh43bx0252"],
[33, "kamothe toll plaza charges paid vehicle no: mh04lq4014"],
[33, "dahisar toll charges exps. for vehicle no: mh43bx7821 paid to ravikiran suryavanshi"],
[33, "airoli toll charges exps.150/- for vehicle no: mh43bx7803 paid to shrikant das"],
[33, "toll charges at dahisar toll plaza vehicle no.: mh43bx7821"],
[33, "airoli toll charges exps. paid to anish kumar vehicle no: mh43bx7803"],
[33, "dahisar toll charges paid to shivshankar yadav vehicle.no: mh04m44896"],
[33, "vashi,airoli & arjunali toll charges paid for vehicle no.mh 43 bx 7803 for the period of to"],
[33, "toll charges vashil toll vehicle no.: mh43bx7803"],
[33, "vashi toll charges for vehicle no.: mh43bx7803"],
[33, "vashi toll charges mh-43-bx-7803"],
[33, "airoli toll plaza charges mh-43-bx-7803"],
[33, "airoli toll charges plaza vehicle no.: mh43bx7803 (16.05..2026"],
[33, "airoli and vashi toll plaza charges vehicle no mh43bx7803"],
[33, "monthly toll charges paid to shrikant das vehicle no.: mh43bx7803"],
[33, "expenses for vashi toll plaza paid for vehicle no.: mh03eg0225"],
[33, "toll charges paid for vehicle no.mh04mh4896"],
[33, "airoli monthly toll plaza charges paid for vehicle no: mh04lq4014"],
[33, "khargar toll charges paid for vehicle no: mh43bx0252"],
[33, "airoli monthly toll pass paid for vehicle no: mh43bx7803"],
[33, "monthly toll charges (vehicle no.mh43bx7821"],
[33, "igatpuri toll charges (vehicle no.mh03eg0225"],
[33, "jalnar- watur toll charges paid for vehicle no.mh04mh4896"],
[33, "kharghar toll charges paid for vehicle no.mh04mh4896"],
[33, "kharghar & kamothe toll charges paid for vehicle no.mh43bx0252"],
[33, "mbpt road toll charges paid for vehicle no.mh43bx7821"],
[33, "mulund toll charges paid for vehicle no.mh43bx7821"],
[33, "kamothe toll charges paid for vehicle no.mh04mh4896"],
[33, "airoli monthly toll chargs paid for vehicle no.mh43bx7821"],
[33, "kamatho toll charges paid for vehicle no.mh04mh4896"],
[34, "cng charges paid for vehicle no. mh 03 eg 0225"],
[34, "deisel charges for vehicle no.: mh43bx7803"],
[34, "cng charges paid for vehicle no: mh03eg0225 for km-73785 (card was not available hence used cash"],
[34, "diesel charges paid for vehicle no.mh43bx0252 (km-76520"],
[34, "petrol charges paid for going to taloja blinkit warehouse"],
[34, "petrol charges paid for going to hira point mahape"],
[34, "c.n.g charges paid for vehicle no.mh03eg0225 (km-49539"]
];
